version: '3'

services:
  nginx:
    image: nginx:v1
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wp-volume:/var/www
    restart: always

  mariadb:
    image: mariadb:v1
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:v1
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/qxia/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/qxia/data/mariadb

networks:
    inception:
      driver: bridge
